---
- name: "Web server"
  hosts: all
  gather_facts: False
  tasks:
  -  name: Install Apache
     yum: 
       name: httpd 
       state: present

  -  name: Start service
     service: 
       name: httpd
       state: started      
